# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 711d8274f4fd46da78155568ccf1789aa199837a1689b104ae642a70215dd8a112928ac44996f62d42a7816528460cc4907d77b3e78bf325d4e3166a2f6a247a

test:
  secret_key_base: a3ce36d836568133ace002f9406238662baeebccf6c4b6e0e6cf1dc3d0a969e2d7adc6eb5152f90ff878abbbaa3cbc6a7fb1b195651f6e4013ca2740ce9b42b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
